### ISSUE TITLE
Correct way to handle a failed async loading of keys

### ISSUE THREAD

**Issue by jpswensen** [piemonte/PBJVideoPlayer#16]
We have been using PBJVideoPlayer and it is awesome.

We are loading a remote m3u8 video and during the initialization of the AVURLAsset, PBJVideoPlayer  loads information about the video asynchronously using loadValuesAsynchronouslyForKeys. The keys that are currently in the list are "tracks", "playable", and "duration". We have one tester who is halfway around the world from our test server that is always having the problem that the "tracks" and "playable" keys succeed with the AVKeyValueStatusLoaded. However, the "duration" key is failing with AVKeyValueStatusFailed.

So, despite searching the Apple documentation and the  internet high and low, I am not exactly sure what to do in this situation and have a few questions:
1) Does AVKeyValueStatusFailed on a single key indicate that the AVAsset won't play? Is "duration" a key that will prevent playback.
2) Can I just re-query that single key with loadValuesAsynchronouslyForKeys and expect that the additional time since the creation of the AVURLAsset will cause it to succeed also?
3) Do I need to re-create the AVURLAsset object?
4) Will calls to [PlayerItem duration] block if this key failed? Will it return the wrong value?

I just can't seem to determine what the behavior will be if I change the code to ignore a failure on "duration" or how to attempt to correct it. Currently the PBJVideoPlayerController returns and never finished initializing the video if any of the key loading fails.

**Comment by rromanchuk** [comment]
#26 Might be related
