### ISSUE TITLE
Add compatibility to iOS7

### ISSUE THREAD

**Issue by brunobasas** [piemonte/PBJVideoPlayer#17]
Not work in iOS7. Video don't load or freeze in a few seconds.

**Comment by piemonte** [comment]
hey @brunobasas thanks for your interest in the project.

the example app compiled for iOS 7 doesn't exhibit the problem you're seeing. if you have other details, let me know.

**Comment by aberror** [comment]
platform:ios,'7.0'
Specs satisfying the `PBJVideoPlayer (~> 0.3.3)` dependency were found, but they required a higher minimum deployment target.
