### ISSUE TITLE
mp4 video not playing from url in pbjvideoplayer

### ISSUE THREAD

**Issue by Moeez007** [piemonte/PBJVideoPlayer#23]
Hello guys I have used the library "pbjvideoplayer" for playing videos from urls. The mp4 video is playing on iOS > 8 and not playing on ios < 8.

video url = http://ivoiceup.com/wework/message_uploads/82208897ae4f9b7d64a50bc70c6cf0a3.mp4

**Comment by rromanchuk** [comment]
Might be related to #26
