### ISSUE TITLE
Sample project, update to show auto-play while scrolling

### ISSUE THREAD

**Issue by piemonte** [piemonte/PBJVideoPlayer#3]
Update the sample project to show auto-play while scrolling

**Comment by mitchellporter** [comment]
@piemonte Have you made any progress on this? I'm planning on implementing this in a future app and would love to see an updated demo or sample code if you've worked on this.

Thanks.

**Comment by piemonte** [comment]
hey @mitchellporter haven't had the opportunity to do this. there's a little discussion about how it's done here, https://github.com/piemonte/Player/issues/12

you just have to set the player's path based on either the scroll velocity slowing down dramatically or stopping. when it starts to scroll again, ensuring the player and cell is properly reset offscreen.

**Comment by mitchellporter** [comment]
@piemonte When you say player, do you mean one individual player for the entire feed of UITableViewCells/UICollectionViewCells? 

I'm curious how you would approach something like this because I'm very fond of your repos and your code quality is great.

I also ask because right now I'm using AVPlayer and I actually have one in each UICollectionViewCell.

**Comment by piemonte** [comment]
@mitchellporter hey there, thanks much for the kind words. so when i say player, i'm referring to the PBJVideoPlayer controller. i haven't focused on an app recently that displays a list of videos so apologies, haven't had a chance to work through an example.

basically, each table cell could manage it's own 'PBJVideoPlayer' controller. the controller would have it's path set based on the scrolling behavior of the scroll view.

there's other ways to do this but that's probably the best method when using this library.

**Comment by mitchellporter** [comment]
@piemonte Gotcha. Right now I'm just using AVPlayer, but I've been able to optimize it and make the scrolling w/ video downloading fairly smooth after hacking around a bit.

Maybe we can collaborate on this feature in the future and setup a nice example in the demo project.

Cheers!

**Comment by georgel** [comment]
@mitchellporter would you consider sharing what you done to avplayer to optimize video download with scrolling? Thank you in advance :)

**Comment by rromanchuk** [comment]
@georgel  I can also share advanced usage as well, but give me the weekend to create a generalized example

**Comment by georgel** [comment]
@rromanchuk Wow! Thank you!  I will take any advice you can share :)

**Comment by kristjanmik** [comment]
any update @mitchellporter  @rromanchuk @georgel ?

**Comment by chlebta** [comment]
@mitchellporter Can you share that please ?

**Comment by justinmakaila** [comment]
@piemonte @mitchellporter I'm extremely curious on what you guys are doing to improve scrolling performance. On the newer devices (6 and 6+), scrolling performance is impacted minimally (occasionally there's a stutter), but on 5 and 5s, a feed of videos using `PBJVideoPlayerController` is practically unusable.

I dug around the code a little bit and noticed that keys are already loaded asynchronously, and the player item's are switched using `replaceCurrentItemWithPlayerItem:`. Are there any other optimizations or pain points you guys are aware of?

**Comment by chlebta** [comment]
@justinmakaila  @piemonte @rromanchuk  @georgel  any updated ?
Also how to integrate the video player inside collectionViewCell ?

**Comment by chlebta** [comment]
@piemonte @rromanchuk  @georgel any update, did Any one succeeded to implement PBJVideoPalyer in tableView or collectionView

**Comment by hemangshah** [comment]
@piemonte @rromanchuk @georgel @chlebta any update, did Any one succeeded to implement PBJVideoPalyer in tableView or collectionView?
