### ISSUE TITLE
PBJVideoPlayerController how to clear current video

### ISSUE THREAD

**Issue by ArkadiYoskovitz** [piemonte/PBJVideoPlayer#30]
Hi,

I'm working on a project that has embedded videos in a UITableView and I'm using the PBJVideoPlayerController for the playback.

But I'm having a problem with clearing the last clip from the player.

the use case goes like this:

you show a video in the top cell and then you scroll the tableview, the scroll pause the playback, after the scroll finishes you load a new video but the player still holds a reference to the old one.

how to i clear the player object?

**Comment by ataranlen** [comment]
You can clear the current video by setting the path to an empty string.

**Comment by piemonte** [comment]
thx @ataranlen
