### ISSUE TITLE
Sound Not Playing

### ISSUE THREAD

**Issue by thejourneydude** [piemonte/PBJVideoPlayer#33]
I'm playing a simple mp4 video and am not receiving any sound from the video. To contrast this, I used your Player lib with the same code and no issues (sound and video worked just fine). I'm bridging this library to my Swift project due to other non-related reasons. Code sample below. 

        self.player = PBJVideoPlayerController()
        
        if let videoPlayer = self.player {
            videoPlayer.view.userInteractionEnabled = true
            
            videoPlayer.view.multipleTouchEnabled = true
            
            videoPlayer.view.frame = self.view.bounds
            
            videoPlayer.playbackFreezesAtEnd = false
            
            videoPlayer.playbackLoops = true
            
            videoPlayer.videoPath = self.ViewControllerVideoPath
            
            self.addChildViewController(videoPlayer)
            
            self.view.addSubview(videoPlayer.view)
            
            videoPlayer.didMoveToParentViewController(self)

            videoPlayer.playFromBeginning()
     }

**Comment by misslester** [comment]
Hi there, thanks for reporting. Looks like the initial volume is initialized to zero. You could probably work around it by setting it to something else. I'll take out that initialization.
