### ISSUE TITLE
Consider making all PBJVideoPlayerControllerDelegate methods optional

### ISSUE THREAD

**Issue by natan** [piemonte/PBJVideoPlayer#41]
@misslester I kinda think all the delegate methods should be optional. It's kinda annoying that if you only care about one of them that you still have to implement the 4 required ones. What do you think?

**Comment by misslester** [comment]
commit 064572725873876fab6d914d3f64d4ebec2956a4
Author: Leslie Nadeau <leslienadeau@gmail.com>
Date:   Sun Dec 13 17:31:43 2015 -0800

    PBJVideoPlayerController, update delegate methods to optional
