### ISSUE TITLE
Expose _avplayer…

### ISSUE THREAD

**Issue by zedrdave** [piemonte/PBJVideoPlayer#49]
Very nice and useful lib…

But not being able to access the underlying _avplayer severely limits its usefulness, since many properties cannot be read/set through it yet. And since it is declared in a class extension, there is no way to use an extension either…

Would you consider moving _avplayer to an instance variable or providing a `getAVPlayer` method?
I can provide PR, but you'll probably be better off doing it your way since it's such a small change…

**Comment by piemonte** [comment]
Hey @zedrdave thanks for the interest in the library! How about we make a private property, as you suggest, that can be accessed through a class extension.. just for now?

I'm on a special contract at the moment that prevents me from making this change myself, but if you can make a pull request or I can ask one of the project collaborators to help out and merge it.

Take care. :v:

**Comment by zedrdave** [comment]
Sure. As long as it can be used without modifying the framework, it works for me :-)

But is there any reason you really don't want to expose it?
