### ISSUE TITLE
What kinds of file do i play?

### ISSUE THREAD

**Issue by yoonyoungji** [piemonte/PBJVideoPlayer#58]
I wonder what kind of files do i play except http://
I want to play avi files  and http streaming files in own app
so please tell me your good video player what to do!!!
as soon as possible

**Comment by piemonte** [comment]
hi @yoonyoungji this is a simple wrapper around AVPlayer, so anything AVPlayer supports.

📎 https://developer.apple.com/reference/avfoundation/avplayer
