### ISSUE TITLE
Video playing black screen on iOS 10, 10.1..

### ISSUE THREAD

**Issue by polihym** [piemonte/PBJVideoPlayer#59]
I faced a critical issue for video playing with PBJVideoPlayer. 
Sometimes, video playing is showing a black screen with only sound. The sound is working good. 
This was worked on iOS 9.x well. 

I am not sure the reason.

Please review that and help soon. 
Looking forward to your fixing or replying
Thanks

**Comment by piemonte** [comment]
hey @polihym thanks for the feedback. if i can repro, i'll check into it. also check out the swift based player, http://github.com/piemonte/Player

📎 https://github.com/piemonte/PBJVideoPlayer/issues/57

**Comment by polihym** [comment]
Thanks for your reply and looking forward to your news soon
