### ISSUE TITLE
a m3u8 can't play

### ISSUE THREAD

**Issue by z7z** [piemonte/PBJVideoPlayer#61]
http://7xldny.com1.z0.glb.clouddn.com/job_video/guide.m3u8
can't play this .
How can do it.
in iOS Safari is OK.

**Comment by piemonte** [comment]
hey @z7z thanks for the project interest. i'm not knowledgable in HLS but there has been a lot of discussion surrounding it at WWDC 2016 for iOS 10:

📎 https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/MediaPlaybackGuide/Contents/Resources/en.lproj/HTTPLiveStreaming/HTTPLiveStreaming.html

The iOS 10 HLS specific api's haven't been added to this project yet but maybe in the future. I'm not using it for my personal projects.
